sonar.organization=readersroom-lab
sonar.projectKey=readersroom-lab_the-reading-room

# Path to source directories (you can add more folders if needed)
sonar.sources=app,components,lib

# Folders to exclude from the scan (like build files and dependencies)
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,public/**
